site_title = "DrugAI MolArxiv"
limit_days = 10
cache_url = "https://robbenplus.github.io/MyArxiv/cache.json"

[[sources]]
limit = 500
category = "cs.LG"
title = "Machine Learning"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
